"""arrumando erro no nome da tabela profileSystem

Revision ID: 2dd809fc3063
Revises: 35c984dd5e6c
Create Date: 2020-10-06 16:17:45.853225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd809fc3063'
down_revision = '35c984dd5e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userProfileSystem', sa.Column('profile_system_id', sa.Integer(), nullable=False))
    op.drop_constraint('userProfileSystem_profileSytem_id_fkey', 'userProfileSystem', type_='foreignkey')
    op.create_foreign_key(None, 'userProfileSystem', 'profileSystem', ['profile_system_id'], ['id'])
    op.drop_column('userProfileSystem', 'profileSytem_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userProfileSystem', sa.Column('profileSytem_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'userProfileSystem', type_='foreignkey')
    op.create_foreign_key('userProfileSystem_profileSytem_id_fkey', 'userProfileSystem', 'profileSystem', ['profileSytem_id'], ['id'])
    op.drop_column('userProfileSystem', 'profile_system_id')
    # ### end Alembic commands ###
